#!/bin/sh
# simple script to flash rp2040

if [ $# -eq 0 ]; then
    echo "$0: usage: $( basename $0 ) <ELF file>"
    exit 1
fi
  
openocd -s $OPENOCD_SCRIPTS \
    -f interface/cmsis-dap.cfg \
    -f target/rp2040.cfg \
    -c "adapter speed 5000" \
    -c "program $1 verify reset exit"

# EOF:
